version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    working_dir: /app/backend
    command: 'npm run start:dev'
    ports:
      - '3001:3001'
    depends_on:
      - db
    env_file: ./backend/.env
    volumes:
      - './:/app/backend'
      - '/app/node_modules'
    networks:
      - node-network

  db:
    image: postgres:latest
    container_name: db_postgres
    volumes:
      - db_volume:/var/lib/postgresql/data 
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - node-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: node:lts-alpine
    working_dir: /app/frontend
    command: "npm run start"
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./frontend/.env
    volumes:
      - './:/app/frontend'
    depends_on:
      - api
    networks:
      - node-network

volumes:
  db_volume:

networks:
  node-network:
    driver: bridge