version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    command: 'npm run start'
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    env_file: .env
    volumes:
      - './src:/app/src'
      - '/app/node_modules'
    networks:
      - node-network

  mongodb:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: node:lts-alpine
    ports:
      - "3000:80"
    restart: always
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge