version: '3'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    working_dir: /app/backend
    command: 'npm run start:dev'
    ports:
      - '3001:3001'
    depends_on:
      - db
    env_file: ./backend/.env
    volumes:
      - './backend/:/app'
      - '/app/node_modules'
    networks:
      - node-network

  db:
    image: postgres:latest
    container_name: db_postgres
    volumes:
      - db_volume:/var/lib/postgresql/data 
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - node-network

volumes:
  db_volume:

networks:
  node-network:
    driver: bridge